import { useEffect, useState } from 'react';
import { Edit3, Loader2, MessageSquare, Plus, X } from 'lucide-react';
import { toast } from 'sonner';
import { createAdminSmsPackage, getAdminSmsPackages, setAdminSmsPackageStatus, updateAdminSmsPackage } from '../../../lib/api.js';
import { formatCurrency } from '../../utils/currency';

const empty = { name:'', total_sms:'', amount:'', no_expiry:true, expiry_days:'', is_active:true };
export default function AdminSmsPackages(){
 const [packages,setPackages]=useState<any[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<any>(null),[open,setOpen]=useState(false),[saving,setSaving]=useState(false);
 const load=async()=>{try{setPackages((await getAdminSmsPackages()).packages||[])}catch(e:any){toast.error(e?.data?.message||'Unable to load packages.')}finally{setLoading(false)}}; useEffect(()=>{load()},[]);
 const show=(p?:any)=>{setEditing(p||null);setForm(p?{...p,total_sms:String(p.total_sms),amount:String(p.amount),expiry_days:p.expiry_days?String(p.expiry_days):''}:empty);setOpen(true)};
 const save=async()=>{try{setSaving(true);const payload={...form,total_sms:Number(form.total_sms),amount:Number(form.amount),expiry_days:form.no_expiry?null:Number(form.expiry_days)};const r=editing?await updateAdminSmsPackage(editing.id,payload):await createAdminSmsPackage(payload);toast.success(r.message);setOpen(false);await load()}catch(e:any){toast.error(e?.data?.message||'Unable to save package.')}finally{setSaving(false)}};
 return <div className="p-4 md:p-7 space-y-6"><div className="flex justify-between items-end"><div><h1 className="text-2xl font-bold text-slate-900">SMS Packages</h1><p className="text-sm text-slate-500">Create prepaid SMS credit packages and control availability.</p></div><button onClick={()=>show()} className="bg-blue-700 text-white rounded-xl px-4 py-2.5 flex gap-2 items-center"><Plus size={16}/>New Package</button></div>
 {loading?<div className="p-16 text-center"><Loader2 className="animate-spin inline"/></div>:<div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-5">{packages.map(p=><div className="bg-white border rounded-2xl p-5" key={p.id}><div className="flex justify-between"><div className="w-10 h-10 rounded-xl bg-blue-100 text-blue-700 flex items-center justify-center"><MessageSquare size={20}/></div><button onClick={()=>show(p)} className="p-2 text-slate-400"><Edit3 size={17}/></button></div><h2 className="font-bold text-slate-900 mt-4">{p.name}</h2><div className="text-3xl font-black text-blue-700 mt-2">{p.total_sms.toLocaleString()} <span className="text-xs text-slate-400">SMS</span></div><div className="font-bold mt-1">{formatCurrency(p.amount)}</div><div className="text-xs text-slate-400 mt-2">{p.no_expiry?'No expiry':`${p.expiry_days} days`} · {p.purchase_count} purchases · {formatCurrency(p.revenue)} revenue</div><button onClick={async()=>{await setAdminSmsPackageStatus(p.id,!p.is_active);load()}} className={`mt-4 w-full py-2 rounded-xl text-sm font-semibold ${p.is_active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{p.is_active?'Active':'Inactive'}</button></div>)}</div>}
 {open&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-lg p-6 space-y-4"><div className="flex justify-between"><h2 className="font-bold text-lg">{editing?'Edit':'Create'} SMS Package</h2><button onClick={()=>setOpen(false)}><X/></button></div><label className="block text-sm">Package name<input className="mt-1 w-full border rounded-xl px-3 py-2.5" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Total SMS<input type="number" min="1" className="mt-1 w-full border rounded-xl px-3 py-2.5" value={form.total_sms} onChange={e=>setForm({...form,total_sms:e.target.value})}/></label><label className="text-sm">Amount (GHS)<input type="number" min="0.01" step="0.01" className="mt-1 w-full border rounded-xl px-3 py-2.5" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label></div><label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={form.no_expiry} onChange={e=>setForm({...form,no_expiry:e.target.checked})}/>No expiry</label>{!form.no_expiry&&<label className="block text-sm">Expiry duration (days)<input type="number" min="1" className="mt-1 w-full border rounded-xl px-3 py-2.5" value={form.expiry_days} onChange={e=>setForm({...form,expiry_days:e.target.value})}/></label>}<label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/>Active</label><button disabled={saving} onClick={save} className="w-full bg-blue-700 text-white rounded-xl py-3 font-semibold disabled:opacity-60">{saving?'Saving...':'Save Package'}</button></div></div>}
 </div>;
}
